name: Build WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
        components: rust-src, llvm-tools-preview
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Install binaryen
      run: sudo apt-get install binaryen
      
    - name: Build
      run: |
        wasm-pack build --target web --release
        wasm-opt -O4 pkg/igl_quant_bg.wasm -o pkg/igl_quant_bg.wasm
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wasm-pkg
        path: pkg/
