name: Build WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
        
    - name: Build
      run: |
        cargo install wasm-pack
        wasm-pack build --target web --release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wasm-pkg
        path: pkg/