name: Build WASM
on: [push, pull_request]

name: Build WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
          components: rust-src

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: wasm-pack build --target web --release

      - name: Verify files
        run: ls -R pkg/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-pkg
          path: pkg/